# Generated by Django 3.2.9 on 2021-11-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='img/about/')),
                ('mission', models.TextField()),
                ('fbLink', models.CharField(blank=True, default='https://www.facebook.com/Montoya-Landscaping-Services-856645058033759', max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default='(443) 605-4933', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, default='Montoya18296@gmail.com', max_length=100, null=True)),
                ('ownerComment', models.TextField()),
                ('crewComment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About',
                'ordering': ['timestamp'],
            },
        ),
    ]
